### ISSUE TITLE
Utiliser s3 pour le stocage des images, des videos, des documents, etc.

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/boost#1]
C'est important d'avoir une stockage de fichiers indépendant de le hébergement parce que les fichiers peuvent être utilisés à d'autres fins que l'illustration du site. C'est important aussi de pourvoir changer d'hébergement si on trouve de coût plus accessible, sans être obligé de migrer tout les données, seulement l'application.

**Comment by Ericboust** [comment]
Nous payons actuellement un hébergement forfaitaire indépendamment du trafic.  le cout des hébergements cloud augmentera avec le trafic!  A discuter!

**Comment by htmfilho** [comment]
Pouvez-vous me dire quel service d'hébergement vous utilisez maintenant et quel plan, afin que je puisse vérifier les exigences techniques?

Pour info: l'hébergement cloud:
EUR 0,10 / 1O gb
EUR 7 / mois (SSL inclus)
C'est moins de EUR 100 / an.

**Comment by htmfilho** [comment]
The current hosting already provides enough space for the needs of the club.
