### ISSUE TITLE
Gestion des demandes d'attestation

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/boost#15]
Les membres du club peuvent sollicités en ligne des attestations (mutuelle, employeur, ...) sans passer par l'administration du club. Tous les infos nécessaires pour produire les documents sont disponible dans la base de données.

La fiche membre doit être actualisée avec les infos de paiement (membre en ordre de paiement ou pas). Si en ordre, impression possible, sinon, pas d'impression.

**Comment by Ericboust** [comment]
POur le moment, nous essayons d'éviter de devoir manipuler et compléter manuellement des documents papier.  Nous envoyons maintenant des documents standards en PDF reprenant les infos nécessaires sur base des infos de la base de données access.  L'idéal serait que les membres puissent demander en ligne ce document ou puisse le créer eux-même.  Cela veut dire que la fiche membre doit être actualisée avec les infos de paiement (membre en ordre de paiement ou pas).  Si en ordre, impression possible, sinon, pas d'impression.
