### ISSUE TITLE
Permetre partager une page du site sur Facebook

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/boost#17]
Ajouter un bouton "Partager sur Facebook" dans tous les pages du site.

**Comment by Ericboust** [comment]
Quand je parlais de lien avec facebook, je pensais également à la possibilité d'être reconnu comme membre grace à mon profil facebook ouvert.

**Comment by htmfilho** [comment]
Salut @Ericboust , le ticket qui correspond au besoin c'est le #19 , mais le ticket #18 devra être fait en priorité parce que il y a toujours des gent sans Facebook.
