### ISSUE TITLE
Gérer le contenu du site web

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/boost#2]
Le site est composé des sections, des pages et de fichiers de media. L'application devra permettre la gestion de présentation, navigation et contenu sans exiger des connaissances techniques des utilisateurs, a par de la connaissance de base informatique pour opérer un ordinateur et naviguer sur internet.

Les sections groupent les pages et organisent la page d'accueil. Les pages montrent effectivement les contenus désirés. La navigation lie les pages et les sections dans une séquence résumé-détail et des infos associés.

La gestion du contenu est entièrement fait dans l'administration. Plusieurs personnes puissent alimenter le site. Il suffit d'avoir le rôle d'auteur ou administrateur pour le faire.

**Comment by Ericboust** [comment]
POur que le site soit vivant, il faut que plusieurs personnes puissent l'alimenter en temps réel.
exemple, 
Il ya 3 ou 4 ans quand un groupe partait en stage, les entraineurs m'envoyait des infos que je remettais en forme et publias dans une page spécifique du site et que j'envoyais également par mail.  Aujourd'hui, les entraîneurs crée un groupe facebook privé.  L'idéal serait qu'il puisse publier directemnt sur le site et que les membres soit liés au site via leur compte facebook et soit ainsi averti d'une nouvelle publication.

**Comment by htmfilho** [comment]
@Ericboust Si l'entraîneur aliment le site, est-ce que son contenu doit passer par une approbation avant d'être publié ou il peux le publier sans restrictions?

Lier les membres au site via Facebook c'est tout à fait possible, mais nous le ferons dans un deuxième moment, lorsque l'enregistrement des membres est en place et entièrement fonctionnel.

**Comment by htmfilho** [comment]
The website administrator has autonomy to manage the content of the disciplines, news and pages.

Groups and partners are still under construction.
