### ISSUE TITLE
Developer l'écran de contact

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/boost#4]
Permettre l'utilisateur d'envoyer des demandes, commentaires, etc., à différentes personnes/fonction du club. L'utilisateur choisira le type de communication, par exemple:

- Inscriptions
- Cours
- Sponsoriser
- Événements
- Bénévole

et après il/elle peux écrire un **titre**, l'**email** et le **message**. Pour éviter des spams, l'utilisateur devra encore passer par une validation captcha qui vérifie se l'utilisateur est bien un être humain.

Pour chaque type de communication, l'administrateur devra indiquer, dans l'administration, l'email de chaque destinataire responsable. l'idée c'est d’éviter que l'utilisateur mémorise les emails.

**Comment by Ericboust** [comment]
Nous pouvons gérer des adresses mail du style contact@boust.be et les rediriger vers l'adresse mail d'une personne chargée (pour une période) de gérer ce type de demande.

**Comment by htmfilho** [comment]
C'est bien fonctionelle.
