### ISSUE TITLE
Gérer les événements d'intérêt de la communauté

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/boost#5]
Le calendrier disponible dans le site actuel est gérer par Google Calendar. Les facilités proposés par Google ne peuvent pas être reproduit facilement dans la nouvelle application et le style du calendrier n'est pas adapté au style du site.

Pour permettre le développement de une série des fonctionnalités demandés (calendrier par groupe, inscriptions aux événements, etc.), c'est nécessaire d’abandonner Google Calendar en faveur d'une solution sur mesure.

Obs.: Dans une deuxième moment, ça sera possible de publier les événements automatiquement sur Google Calendar après la création/modification d'un événement dans l'application (https://developers.google.com/google-apps/calendar/overview).

**Comment by Ericboust** [comment]
Attention, les solutions sur mesure demandent de la programmation spécifique qui devient vite obsolète ou des connaissances informatiques qui ne seront peut-être plus présentes dans le futur.  A éviter si possible.

**Comment by htmfilho** [comment]
@Ericboust En dehors de la gestion de contenu, je ne vois pas une seule fonctionnalité demandé qui ne nécessite pas de programmation. Moi, je ne connais pas de solution pratique qui permet ce niveau de contrôle en ligne sans programmation.

La stratégie qui je vous propose pour combattre l’obsolescence de l'application c'est de la mettre disponible comme open source et essayer de construire une communauté au tour du projet. Cette communauté sera probablement formée par d'autres clubs. En tout cas, nous pouvons toujours trouver des personnes intéressées à contribuer.

Qu'est-ce que vous pensez?

**Comment by htmfilho** [comment]
Pour le moment, les événements sont gérés via la page Facebook.
