### ISSUE TITLE
Déveloper un Newsletter

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/boost#7]
Infos aux utilisateurs qui ont souhaité être informé des mises à jour du contenu publique du site, sans nécessairement être membre du club. Il suffit d'informer l’adresse email. Les infos exclusives pour les membres ne font pas partie du newsletter.

**Comment by Ericboust** [comment]
Attention, les mises à jour de pages du site doivent être filtrée dans certains cas (partie spécifique membre)

**Comment by htmfilho** [comment]
The Facebook page seems to be more effective in that sense.
