### ISSUE TITLE
Calendrier du groupe

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/boost#8]
Chaque groupe a son propre calendrier qui affiche les événements communs à tous et les événements propre au groupe. Les membres et les instructeurs du groupe pouvons consulter le calendrier dans leurs profils.

Le calendrier est rempli par défaut par l'horaire standard du groupe. La mise à jour peut-être effectuée par les administrateurs et/ou les entraîneurs en charge du groupe.

**Comment by Ericboust** [comment]
le calendrier est rempli par défaut par l'horaire standard du groupe.  La mise à jour peut-être effectuée par les administrateurs et/ou les entraîneurs en charge du groupe
