### ISSUE TITLE
Tableau des présences des membres aux entraînements

### ISSUE THREAD

**Issue by htmfilho** [htmfilho/boost#9]
L'entraîneur peux contrôler la présence/absence des membres de ses groupes. 

Comme ce n'est pas pratique d'apporter un ordinateur au bord de la piscine, l'entraîneur utilisera de papier dans un premier moment. L'entraîneur utilise l'application pour imprimer la liste des membres de chaque groupe. Chaque impression permettre d'encoder tous les séances d'un groupe.

Après chaque séance ou après un certain nombre des séances prédéterminé, l'entraîneur devra encoder les présences en ligne.

**Comment by Ericboust** [comment]
Ce module devrait également permettre de comptabiliser les heures prestées par l'entraîneur (heure d'arrivée et de départ)
la plupart des entraineurs ont un smartphone et devraient pouvoir encoder les présences en live pour éviter l'étape papier.

**Comment by htmfilho** [comment]
@Ericboust j'ai créé un autre ticket (#16) pour l'enregistrement des heures prestées par l'entraîneur. Comme ça on peux se concentrer sur les membres dans celui-ci. Je vais répondre à votre commentaire là bas.
